#!/bin/bash
python server.py config.txt localhost 5001 &
python server.py config.txt localhost 5002 &
#python server.py config.txt localhost 5003 &
#python server.py config.txt localhost 5004 &
#python server.py config.txt localhost 5005 &
#python server.py config.txt localhost 5006 &
#python server.py config.txt localhost 5007 &
#python server.py config.txt localhost 5008 &
#python server.py config.txt localhost 5009 &
#python server.py config.txt localhost 5010 &
#python server.py config.txt localhost 5011 &
#python server.py config.txt localhost 5012 &
#python server.py config.txt localhost 5013 &
#python server.py config.txt localhost 5014 &
#python server.py config.txt localhost 5015 &
#python server.py config.txt localhost 5016 &
#python server.py config.txt localhost 5017 &
#python server.py config.txt localhost 5018 &
#python server.py config.txt localhost 5019 &
#python server.py config.txt localhost 5020 &
